version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: bumdes
      POSTGRES_PASSWORD: bumdes123
      POSTGRES_DB: si_bumdes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bumdes -d si_bumdes"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
